#!/bin/sh

NAME="exit"
PURPOSE="Exits from this shell."

case "$1" in
    -help|-h)
        echo "Usage: $NAME"
        echo $PURPOSE
        exit
        ;;
    -purpose)
        echo $PURPOSE
        exit
        ;;
esac

exit 251
